spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: 'false'
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
        ddl-auto: update
    show-sql: 'true'
    generate-ddl: true
  datasource:
    username: wsluser
    url: jdbc:postgresql://localhost:5433/wslLogger
    password: 1234
    driver-class-name: org.postgresql.Driver




